language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install -U -r requirements.txt
    - buildout
script:
    - bin/test
notifications:
    email: false
cache: pip
